// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyATJNLTmXxJOx2BVSmQkao4q3ozyVbw4',
    appId: '1:18607328866:web:6b9ca8eca3aac49b3c8b3b',
    messagingSenderId: '18607328866',
    projectId: 'jhattasamachaar',
    authDomain: 'jhattasamachaar.firebaseapp.com',
    storageBucket: 'jhattasamachaar.appspot.com',
    measurementId: 'G-KMXBFGNPCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFdcNg_Ols8G8k2fiVzFSOBFU78QhbnmE',
    appId: '1:18607328866:android:9c0a0d70cc55068d3c8b3b',
    messagingSenderId: '18607328866',
    projectId: 'jhattasamachaar',
    storageBucket: 'jhattasamachaar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDty8S3lmItKs0liWlXGKzQrf9Aj1TaALk',
    appId: '1:18607328866:ios:664dc4e5542626533c8b3b',
    messagingSenderId: '18607328866',
    projectId: 'jhattasamachaar',
    storageBucket: 'jhattasamachaar.appspot.com',
    iosBundleId: 'com.example.jhattasamachar',
  );
}
